# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-84HLH44SMJ"
    anonymize_ip         : # true, false (default)
